### PR TITLE
fix(log): uniform log levels

### LINKED ISSUE #48: [DOCS] endure and plugins logger use different log level naming
i was trying to set the log level `warning` but i should have been using `warn` instead

in https://github.com/spiral/roadrunner-docs/blob/master/beep-beep/logging.md and https://github.com/spiral/roadrunner-docs/blob/master/intro/config.md the log levels are defined as
```
Levels: panic, error, warning, info, debug. Default: debug.
```
and
```
  # Logging level can be "panic", "error", "warning", "info", "debug".
```

but endure logger and plugins logger use diferent methods to interpret log level

endure: https://github.com/spiral/roadrunner-binary/blob/50d2aaff4655edc2c36ef0d91dbce114267e48f1/internal/container/config.go
plugins:
https://github.com/uber-go/zap/blob/c23abee72d197be00f17816e336aca5c72c6f26a/zapcore/level.go#L126-L146
called from https://github.com/spiral/roadrunner/blob/009b7009885d8a15e6fa6c7e78436087b2f20129/plugins/logger/config.go#L106

it's confusing for the endure and plugin log level to use different naming
it might be good idea to either correct the documentation or correct the code to use the same log level naming

I tried this code:

```go
endure:
  log_level: "warning"

logs:
  mode: production
  level: warning
```

I expected to see this happen: only warning and higher logs

Instead, this happened: bunch of info logs from plugins specifically metrics plugin

The version of RR used: 2.1.1

### PR DESCRIPTION
**Pull request by 48d90782**
# Reason for This PR

closes #48 

## Description of Changes

- Uniform log levels (warning -> warn)

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

File: internal/container/config.go [hunk 1]
```diff
@@ -69,7 +69,7 @@ func parseLogLevel(s string) (endure.Level, error) {
 		return endure.DebugLevel, nil
 	case "info":
 		return endure.InfoLevel, nil
-	case "warning":
+	case "warn":
```
Comment (tarampampam) [inline internal/container/config.go:72]:
```suggestion
	case "warn", "warning": // keep in mind - `warning` is an alias for `warn`
```

For the backward compatibility?

File: internal/container/config_test.go [hunk 2]
```diff
@@ -53,7 +53,7 @@ func TestNewConfig_LoggingLevels(t *testing.T) {
 	}{
 		{giveLevel: "debug", wantLevel: endure.DebugLevel},
 		{giveLevel: "info", wantLevel: endure.InfoLevel},
-		{giveLevel: "warning", wantLevel: endure.WarnLevel},
+		{giveLevel: "warn", wantLevel: endure.WarnLevel},
```
Comment (tarampampam) [inline internal/container/config_test.go:56]:
```suggestion
		{giveLevel: "warn", wantLevel: endure.WarnLevel},
		{giveLevel: "warning", wantLevel: endure.WarnLevel},
```

**Review by tarampampam — COMMENTED** [review]
backward compatibility?

File: internal/container/config.go (hunk 1 above)
Comment (48d90782) [reply internal/container/config.go:72]: Yeah, it makes sense.

**Comment by tarampampam** [comment]
One more question - what is the reason for `static` plugin removal?

https://github.com/spiral/roadrunner-binary/pull/50/commits/5b1ded8acb7a0759d9e3e9eeb9277c949ac2190e#diff-50eb6d5221176c611088b8c43f4f3ebab4af2e44c15ae9ff578d70773260a95dL45

File: internal/container/plugins.go [hunk 3]
```diff
@@ -41,8 +40,6 @@ func Plugins() []interface{} {
 		// service plugin
 		&service.Plugin{},
 
-		// static
-		&static.Plugin{},
```
Comment (tarampampam) [inline internal/container/plugins.go:45]: One more question - what is the reason for `static` plugin removal?

Comment (48d90782) [reply internal/container/plugins.go:45]: It's not actually removed; it's reworked. Because previously, it was used as middleware on the main HTTP path. That was very hard to implement a proper static handler, `etags,` and central file server. It was merged into the HTTP plugin with a separate file server on the own path (which can be set by the new config options). As for the config - it stays like previous to have backward compatibility with a few new options.
```yaml
    static:
        dir: "."
        pattern: "/tests/"
        forbid: [""]
        allow: [".txt", ".php"]
        request:
            "input": "custom-header"
        response:
            "output": "output-header"
```

Comment (48d90782) [reply internal/container/plugins.go:45]: see: https://github.com/spiral/roadrunner/pull/646
